// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WuWHO_Web_App.Data;

namespace WuWHO_Web_App.Migrations
{
    [DbContext(typeof(WuWHO_Context))]
    partial class WuWHO_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WuWHO_Web_App.Models.WuWHO_db", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MAC_ID")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("RSSI")
                        .HasColumnType("int");

                    b.Property<DateTime>("time_rec")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("tbl_environment_4");
                });
#pragma warning restore 612, 618
        }
    }
}
